되자~

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -3,13 +3,13 @@ name: Spring Boot CI/CD Pipeline
 on:
   push:
     branches:
-      - main
+      - develop
   pull_request:
     branches:
-      - main
+      - develop
 
 env:
-  JAR_FILE: ${{ secrets.JAR_FILE }}  # GitHub Secrets에서 JAR 파일 이름 가져오기
+  JAR_FILE: ${{ secrets.JAR_FILE }}
 
 jobs:
   build:
@@ -25,6 +25,13 @@ jobs:
         java-version: '17'
         distribution: 'temurin'
 
+    - name: Cache Gradle packages
+      uses: actions/cache@v3
+      with:
+        path: ~/.gradle/caches
+        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
+        restore-keys: ${{ runner.os }}-gradle
+
     - name: Grant execute permission for gradlew
       run: chmod +x ./gradlew
 
@@ -34,10 +41,16 @@ jobs:
     - name: Run Tests
       run: ./gradlew test
 
+    - name: Upload build artifacts
+      uses: actions/upload-artifact@v3
+      with:
+        name: Package
+        path: build/libs
+
   deploy:
     runs-on: ubuntu-latest
     needs: build
-    if: github.ref == 'refs/heads/main'
+    if: github.ref == 'refs/heads/develop'
 
     steps:
     - name: Checkout code
@@ -49,6 +62,12 @@ jobs:
         java-version: '17'
         distribution: 'temurin'
 
+    - name: Download build artifacts
+      uses: actions/download-artifact@v3
+      with:
+        name: Package
+        path: build/libs
+
     - name: Add SSH key
       uses: shimataro/ssh-key-action@v2
       with:
@@ -57,6 +76,10 @@ jobs:
 
     - name: Deploy to EC2
       run: |
+        if [ ! -f build/libs/${{ secrets.JAR_FILE }} ]; then
+          echo "JAR file not found"
+          exit 1
+        fi
         scp build/libs/${{ secrets.JAR_FILE }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.DEPLOY_DIR }}/
         ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
           cd ${{ secrets.DEPLOY_DIR }}
